title: Dextera Wiki
description: Official documentation and wiki for Dextera Launcher by Dextera Labs — a modern Android home screen.
baseurl: "/DexteraWiki"
url: "https://miketblountworks.github.io"
lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - vendor

defaults:
  - scope:
      path: ""
    values:
      layout: default
